services:
  # 1. Database
  # db:
  #   image: postgres:15-alpine
  #   container_name: shopstack_db
  #   restart: always
  #   environment:
  #     - POSTGRES_DB=${DB_NAME:-shopstack_db}
  #     - POSTGRES_USER=${DB_USER:-shopstack_admin}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD:-admin_pass_789}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   ports:
  #     - "5433:5432"


  # 2. Backend Django App
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # Command mein entry point so automatic migrations runs
    # command: /app/entrypoint.sh python manage.py runserver 0.0.0.0:8000
    command: ["sh", "-c", "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"]
    volumes:
      - ./backend:/app
      - /usr/local/lib/python3.13/site-packages/ # Django library protection
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    #for outer network connectivity so use here dns
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.base
    # depends_on:
      # - db
      # - redis

  # 3. Frontend React App (Vite)
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    depends_on:
    - backend


  #  4. Redis
  # redis:
  #   image: redis:7-alpine
  #   ports:
  #     - "6379:6379"


  # 5. Celery Worker
  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # command: celery -A config worker --loglevel=info
    command: ["celery", "-A", "config", "worker", "--loglevel=info", "--concurrency=1"]
    volumes:
      - ./backend:/app
      - /usr/local/lib/python3.13/site-packages/
    env_file:
      - ./backend/.env
    dns:
      - 8.8.8.8
      - 1.1.1.1
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.base
    depends_on:
      # - redis
      # - db
      - backend

volumes:
  postgres_data: