# Generated by Django 4.2.11 on 2026-05-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='full_name',
            new_name='name',
        ),
    ]
